apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-node-network-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ayaaya200570-bot/multi-node-network.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true